api:
  dashboard: true   # toggle to false in production

log:
  level: INFO

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"

  traefik:
    address: ":8080"

ping:
  entryPoint: "traefik"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    network: americana_net
    exposedByDefault: false

  file:
    directory: /etc/traefik/dynamic
    watch: true

certificatesResolvers:
  le:
    acme:
      email: admin@americanaamplified.com
      storage: /letsencrypt/acme.json
      httpChallenge:               # ✅ Add this block
        entryPoint: web            # ← tells Traefik to use port 80 for HTTP-01 validation

